apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: your-namespace
  labels:
    app: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      # If you use a private registry, add imagePullSecrets here
      # imagePullSecrets:
      #   - name: regcred
      containers:
      - name: nginx
        # Replace with your image (Docker Hub or ECR): e.g. myuser/nginx-app:latest or 123456789012.dkr.ecr.us-east-1.amazonaws.com/nginx-app:latest
        image: REPLACE_WITH_IMAGE
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
