apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: your-namespace
spec:
  type: LoadBalancer    # Use LoadBalancer for public access on EKS (creates an ELB)
  selector:
    app: nginx-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
